require:
  - rubocop-rails
AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'Gemfile'
    - 'lib/tasks/**'
    - 'bin/*'
    - 'test/**'
    - 'spec/spec_helper.rb'
    - 'Rakefile'
    - 'config.ru'
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: false
