#  https://circleci.com/docs/ja/2.0/language-ruby/
version: 2
jobs:
  build:
    working_directory: ~/api
    docker:
      - image: circleci/ruby:2.6.5
        environment:
          RAILS_ENV: test
      - image: circleci/mysql:5.7
        environment:
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: api_test
    steps:
      - checkout

      - restore_cache:
          keys:
            - rails-demo-{{ checksum "Gemfile.lock" }}
            - rails-demo-
      - run:
          name: Install dependencies
          command: bundle check || bundle install -j4
      - save_cache:
          key: rails-demo-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Wait DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run:
          name: Database Setup
          command:
            bundle exec rake db:create
            bundle exec rake db:structure:load
#      - run:
#          name: Run Rubocop
#          command: bundle exec rubocop
#      - run:
#          name: Run RSpec
#          command: bundle exec rspec
