version: 2
jobs:
  build:
    working_directory: ~/api
    docker:
      - image: circleci/ruby:2.6.0
        environment:
          RAILS_ENV: test
      - image: circleci/mysql:5.7
        environment:
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: password
    steps:
      - checkout

      - restore_cache:
          keys:
            - rails-demo-{{ checksum "Gemfile.lock" }}
            - rails-demo-
      - run:
          name: Install dependencies
          command: bundle install -j4 --path vendor/bundle
      - save_cache:
          key: rails-demo-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Database Setup
          command: |
            bundle exec rake db:create
            bundle exec rake db:migrate
      - run:
          name: Rubocop
          command: bundle exec rubocop
      - run:
          name: Parallel RSpec
          command: bundle exec rspec
      - store_test_results:
          path: /tmp/test-results
